name: Build and push pihole-unbound-hyperlocal

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        user: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: /docker-build
        file: ./Dockerfile
        platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pihole-unbound-hyperlocal:`cat VERSION`,${{ secrets.DOCKER_HUB_USERNAME }}/pihole-unbound-hyperlocal:latest
